backend:
  name: git-gateway
  branch: master

# when using the default proxy server port
local_backend: true

site_url: https://eroyx.tk
display_url: https://eroyx.tk
logo_url: https://eroyx.tk/assets/images/cms.png

media_folder: "uploads"
collections:
  - label: "Icons"
    name: "icons"
    folder: "_icons"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    delete: false
    editor:
      preview: false
      delete: false
    fields:
      - label: "Icon Publish Date"
        name: "date"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        picker_utc: true
      - label: "Icon Shortcode"
        name: "name"
        widget: "string"
        required: true
        hint: "Ex: icon-1password"
      - label: "Display Name"
        name: "display_name"
        widget: "string"
        required: true
        hint: "Ex: 1Password"
      - label: "icon code"
        name: "code"
        widget: "string"
        required: true
        hint: "Ex: f1cb"
      - label: "icon category"
        name: "type"
        widget: "select"
        options:
          - { label: "Fairy Tale Icons", value: "Fairy Tale"}
          - { label: "Halloween Costumes Icons", value: "Halloween Costumes"}
          - { label: "Laboratory Icons", value: "Laboratory"}
          - { label: "Halloween Party Icons", value: "Halloween Party"}
        required: true
        hint: "Ex: halloween-costumes"